[package]
name = "aeo-fixture-desk-app"
version = "0.0.2"
edition = "2021"

[lib]
name = "aeo_fixture_desk_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
aeo-fixture-desk-core = { path = ".." }
tauri = { version = "2", features = [] }

[dev-dependencies]
serde_json = "1.0"
